config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"

# rubocop:disable Metrics/BlockLength
Rails.application.routes.draw do
  namespace :asp do
    resources :schoolings, only: %i[index show] do
      member do
        post :generate_liquidation
        get :download_liquidation
      end
    end

    devise_for :users, skip: :all, class_name: "ASP::User"
  end

  # this allows overriding the redirect-if-not-logged-in path that
  # Devise automatically looks for with "new_#{resource}_session_url"
  # path[1], but we need to get it out of the scoped block above
  # otherwise it ends up being `asp_new_asp_user_session_path`.

  # [1]: https://github.com/heartcombo/devise/blob/bb18f4d3805be0bf5f45e21be39625c7cfd9c1d6/lib/devise/failure_app.rb#L140
  get "asp/login", to: "asp/application#login", as: :new_asp_user_session

  delete "asp/logout", to: "asp/application#logout", as: :destroy_asp_user_session

  namespace :academic do
    root to: "application#home"
    get "home", to: "application#home"
    get "academic_map", to: "application#academic_map"

    resources :establishments, only: [:show] do
      member do
        get :users
      end
      resources :classes, only: [:index]
    end

    resources :classes, only: [:show]

    resource :students do
      get :search_results
    end

    resources :students do
      get :show
      resources :pfmps, only: [:show]
    end

    resources :school_years, path: :year, only: [] do
      get "selected"

      collection do
        get "select"
      end
    end

    resources :users, only: [:index]

    resource :users, only: [] do
      get "select_academy"
      post "set_selected_academy"
    end

    resources :tools, only: [:index] do
      collection do
        post "remove_keycloak_user"
        post "invite_keycloak_user"
        get "academic_invitations"
        get "establishment_invitations"
      end
    end

    resources :academic_invitations, only: [:destroy]

    resources :reports, only: %i[index show] do
      collection do
        get :global_evolution
        post :export_evolution
      end
      member do
        get :global
        post :export
        get :establishments_table
      end
    end

    devise_for :users, class_name: "Academic::User"
  end

  get "academic/login", to: "academic/application#login", as: :new_academic_user_session

  delete "academic/logout", to: "academic/application#logout", as: :destroy_academic_user_session

  resources :users, only: :update do
    get "select_establishment"
  end

  resources :establishments, only: %w[edit update] do
    resources :invitations
  end

  resource :students do
    get "search_results"
  end

  resources :students, only: %i[show] do
    resources :ribs, only: %i[new create update edit]
  end

  resources :school_years, path: :year, only: [] do
    get "selected"

    collection do
      get "select"
    end

    get "/home", to: "home#home"

    resources :establishments, only: [] do
      post "create_attributive_decisions"
      post "reissue_attributive_decisions"
      post "download_attributive_decisions"
    end

    resources :classes, only: %i[show index] do
      member do
        get "bulk_pfmp"
        post "create_bulk_pfmp"
        get "bulk_pfmp_completion"
        put "update_bulk_pfmp"
        get "validation", to: "validations#show"
        post "validation", to: "validations#validate"
      end

      resources :ribs, only: [] do
        collection do
          get "missing"
          post "bulk_create"
        end
      end

      resources :schoolings, only: [:update] do
        member do
          get "confirm_abrogation"
          delete "abrogate_decision"
          get "confirm_cancellation_decision"
          get "cancellation_decision"
          get "confirm_da_extension"
          get "confirm_removal"
          get "confirm_removal_cancellation"
          post "remove"
          post "create_attributive_decision"
        end

        resources :pfmps, except: :index do
          member do
            post :validate
            get :confirm_deletion
            get :confirm_rectification
            post :rectify
            resources :payment_requests, only: %i[create update]
          end
        end
      end
    end

    resources :validations, only: :index
    resources :abrogations, only: :index
  end

  devise_scope :asp_user do
    get "/auth/asp/callback", to: "users/omniauth_callbacks#asp"
    post "/auth/asp_developer/callback", to: "users/omniauth_callbacks#asp_developer"
  end

  devise_scope :academic_user do
    get "/auth/academic/callback", to: "users/omniauth_callbacks#academic"
    post "/auth/academic_developer/callback", to: "users/omniauth_callbacks#academic_developer"
  end

  devise_for :users

  devise_scope :user do
    %w[fim masa developer].each do |action|
      match "/users/auth/#{action}/callback", to: "users/omniauth_callbacks##{action}", via: %i[get post]
    end

    get "/users/auth/failure", to: "users/omniauth_callbacks#failure"

    get "login", to: "home#login", as: :new_user_session
    delete "sign_out", to: "devise/sessions#destroy", as: :destroy_user_session
  end

  root "home#index"

  get "/welcome", to: "home#welcome"
  get "/home", to: "home#home"
  get "/accessibility", to: "home#accessibility"

  get "/maintenance", to: "home#maintenance"
  get "/legal", to: "home#legal"
  get "/faq", to: "home#faq"

  resources :stats, only: [:index] do
    collection do
      get "paid_pfmps_per_month"
    end
  end

  if Rails.env.production?
    Sidekiq::Web.use(Rack::Auth::Basic) do |user, password|
      # https://github.com/sidekiq/sidekiq/wiki/Monitoring#rails-http-basic-auth-from-routes
      # Protect against timing attacks:
      # - See https://codahale.com/a-lesson-in-timing-attacks/
      # - See https://thisdata.com/blog/timing-attacks-against-string-comparison/
      # - Use & (do not use &&) so that it doesn't short circuit.
      # - Use digests to stop length information leaking

      allowed_user = Digest::SHA256.hexdigest(ENV.fetch("APLYPRO_SIDEKIQ_USER", nil))
      allowed_password = Digest::SHA256.hexdigest(ENV.fetch("APLYPRO_SIDEKIQ_PASSWORD", nil))

      Rack::Utils.secure_compare(Digest::SHA256.hexdigest(user), allowed_user) &
        Rack::Utils.secure_compare(Digest::SHA256.hexdigest(password), allowed_password)
    end
  end

  mount Sidekiq::Web => "/sidekiq"
end
# rubocop:enable Metrics/BlockLength

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  layout "maintenance", only: :maintenance

  skip_before_action :authenticate_user!, only: %i[maintenance index login legal]

  before_action :show_welcome_screen, only: :home
  before_action :infer_page_title, except: %i[index maintenance]

  def index
    redirect_to school_year_home_path(SchoolYear.current) and return if user_signed_in?

    redirect_to new_user_session_path
  end

  def home
    @inhibit_title = true

    @establishment_facade = EstablishmentFacade.new(current_establishment, selected_school_year)
  end

  def welcome
    @inhibit_banner = true
    @inhibit_nav = true

    current_user.update!(welcomed: true)
  end

  def maintenance
    redirect_to root_path and return if !maintenance_mode?

    @msg = ENV.fetch("APLYPRO_MAINTENANCE_REASON")
  end

  def login; end

  def legal; end

  def faq
    @inhibit_title = true
  end

  def accessibility; end

  private

  def show_welcome_screen
    redirect_to welcome_path and return unless current_user.welcomed?
  end
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
  def attributive_decisions_download_button
    count = current_establishment.schoolings.with_attributive_decisions
                                 .joins(:classe)
                                 .where(classe: { school_year: selected_school_year })
                                 .count

    button_to(
      t("panels.attributive_decisions.download", count: count),
      school_year_establishment_download_attributive_decisions_path(selected_school_year, current_establishment),
      method: :post,
      class: "fr-btn fr-btn--primary",
      data: { turbo: false }
    )
  end

  def attributive_decisions_generation_form
    count = current_establishment.schoolings.without_attributive_decisions
                                 .joins(:classe)
                                 .where(classe: { school_year: selected_school_year })
                                 .count

    render partial: "home/attributive_decision_form", locals: { establishment: current_establishment, count: count }
  end

  def cannot_generate_attributive_decisions_button
    button_to(
      t("panels.attributive_decisions.not_allowed"),
      "#",
      class: "fr-btn fr-btn--primary",
      disabled: true
    )
  end

  def confirmed_director_information
    return if current_user.selected_establishment.confirmed_director.blank? || current_user.confirmed_director?

    I18n.t(
      "panels.attributive_decisions.confirm_director_information",
      name: current_user.selected_establishment.confirmed_director.name
    )
  end
end

app/views/home/_attributive_decision_form.html.haml
= form_with method: :post, url: school_year_establishment_create_attributive_decisions_path(selected_school_year, establishment), data: { controller: "confirm-director" } do |form|
  .fr-checkbox-group
    = form.check_box :confirmed_director, { checked: current_user.confirmed_director?, id: "create_confirmed_director", data: { confirm_director_target: "checkbox", action: "change->confirm-director#toggleSubmitButton" } }, "1", "0"
    %label.fr-label{for: "create_confirmed_director"}
      = t("panels.attributive_decisions.confirm_director").html_safe
      .fr-text--sm.fr-mt-1w= confirmed_director_information

  = form.submit t("panels.attributive_decisions.generate", count: count), class: "fr-btn fr-btn--secondary", data: { confirm_director_target: "submit" }

app/views/home/_attributive_decision_reissue_form.html.haml
%section.fr-accordion
  %h3.fr-accordion__title
    %button.fr-accordion__btn{"aria-controls" => "accordion-106", "aria-expanded" => "false"}
      Rééditer les décisions d'attribution précédemment éditées
  .fr-collapse#accordion-106
    = form_with method: :post, url: school_year_establishment_reissue_attributive_decisions_path(selected_school_year, current_establishment), data: { controller: "confirm-director" } do |form|
      .fr-checkbox-group
        = form.check_box :confirmed_director, { checked: current_user.confirmed_director?, id: "reissue_confirmed_director", data: { confirm_director_target: "checkbox", action: "change->confirm-director#toggleSubmitButton" } }, "1", "0"
        %label.fr-label{for: "reissue_confirmed_director"}
          = t("panels.attributive_decisions.confirm_director").html_safe
          .fr-text--sm.fr-mt-1w= confirmed_director_information
      = form.submit "Rééditer les décisions d'attribution", class: "fr-btn fr-btn--secondary", data: { confirm_director_target: "submit" }

app/views/home/_home_timeline.html.haml
= render 'school_years/announcement'

.row
  %h1= "Année scolaire #{selected_school_year}"

- if @establishment_facade.students_count <= 0
  .row
    = t("errors.school_years.not_found").html_safe
- else
  - dsfr_colors = { blue: "#000091", light_blue: "#bccdff", green: "#88fdaa", red: "#ffbdbd" } # https://www.systeme-de-design.gouv.fr/fondamentaux/couleurs-palette
  = turbo_frame_tag "home_charts" do
    .fr-grid-row.timeline-row
      .fr-col-md-7
        .gray-panel.timeline-section
          = render 'classes/attributive_decisions_panel'
      .fr-col-md-4.fr-ml-4w
        .chart-container
          = pie_chart({ "Élèves avec DA" => @establishment_facade.attributive_decisions_count, "Élèves sans DA" => @establishment_facade.without_attributive_decisions_count }, colors: [dsfr_colors[:green], dsfr_colors[:red]], donut: true)

    .fr-grid-row.timeline-row
      .fr-col-md-7
        .gray-panel.timeline-section
          .fr-grid-row.fr-grid-row--top
            %h2.fr-col 2. Coordonnées bancaires
            = ribs_progress_badge(current_establishment.schoolings, title: "Les coordonnées bancaires sont réutilisées pour un même élève\nà travers toutes les classes qu'il a pu fréquenter.")
          %p Afin de pouvoir verser l'allocation aux lycéens, APLyPro a besoin de leurs coordonnées bancaires, de celles d'un responsable légal ou d'un tiers.
          %ul.fr-btns-group
            %li= link_to "Choisir une classe pour saisir des coordonnées bancaires", school_year_classes_path(selected_school_year), class: "fr-btn fr-btn--primary fr-mb-0", data: { turbo_frame: "_top" }
      .fr-col-md-4.fr-ml-4w
        .chart-container
          = pie_chart({ "Élèves avec RIB" => @establishment_facade.ribs_count, "Élèves sans RIB" => @establishment_facade.students_without_rib_count }, colors: [dsfr_colors[:green], dsfr_colors[:red]], donut: true)

    .fr-grid-row.timeline-row
      .fr-col-md-7
        .gray-panel.timeline-section
          %h2 3. Périodes de formation en milieu professionnel
          .fr-grid-row
            - PfmpStateMachine.states.each_with_index do |state, index|
              - if index > 0
                .fr-mx-1w →
              = pfmps_status_count_badge(state.to_sym, @establishment_facade.pfmps_counts[state.to_sym], display_zero: true)
          %p Pour calculer le montant des allocations à envoyer, APLyPro a besoin de connaître le nombre de jours travaillés des PFMPs de chaque élève.
          %ul.fr-btns-group
            %li= link_to "Choisir une classe ou un élève pour saisir une PFMP", school_year_classes_path(selected_school_year), class: "fr-btn fr-btn--primary fr-mb-0", data: { turbo_frame: "_top" }
      .fr-col-md-4.fr-ml-4w
        .chart-container
          = column_chart(@establishment_facade.pfmps_counts.transform_keys { |key| t("pfmps.state.#{key}") },
            colors: [dsfr_colors[:light_blue], dsfr_colors[:red], dsfr_colors[:green], dsfr_colors[:red]],
            label: "PFMPs par états")

    .fr-grid-row.timeline-row
      .fr-col-md-7
        .gray-panel.timeline-section
          %h2 4. Demandes de paiements des PFMPs
          .fr-grid-row
            - ASP::PaymentRequestDecorator::PAYMENT_STAGES.each_with_index do |states, index|
              - if index > 0
                .fr-mx-1w →
              .centering-container.fr-mb-2w
                = payment_requests_status_count_badge(states.first, @establishment_facade.payment_requests_counts[states.first], display_zero: true)
                = payment_requests_status_count_badge(states.last, @establishment_facade.payment_requests_counts[states.last], display_zero: false)
          %p La validation du chef d'établissement est nécessaire pour chaque PFMP. Une fois la PFMP validée, une demande de paiement est ensuite envoyée à l'Agence de Services et de Paiement (ASP). Chaque demande de paiement possède un statut affiché dans la page "Paiements".
          %ul.fr-btns-group
            - if current_user.can_validate?
              %li= link_to "Consulter et gérer les envois en paiement", school_year_validations_path(selected_school_year), class: "fr-btn fr-btn--primary fr-mb-0", data: { turbo_frame: "_top" }
            - else
              %li= button_to "Vous n'avez pas le droit de valider des PFMPs", "#", class: 'fr-btn fr-btn--primary fr-mb-0', disabled: true
      .fr-col-md-4.fr-ml-4w
        .chart-container
          = column_chart(@establishment_facade.payment_requests_counts.transform_keys { |key| t("payment_requests.state.#{key}") },
            colors: [dsfr_colors[:blue], dsfr_colors[:red], dsfr_colors[:light_blue], dsfr_colors[:red], dsfr_colors[:green], dsfr_colors[:red]],
            label: "Demandes de paiements par états")

app/views/home/faq.html.haml
= render 'shared/faq'

app/views/home/home.html.haml
.home.fr-container
  .fr-grid-row.fr-grid-row--center
    - if Exclusion.establishment_excluded?(current_establishment.uai, selected_school_year)
      = dsfr_alert(type: :warning, title: "Impossible de récupérer les élèves") do
        %p Il est impossible de récupérer les données de vos élèves, cet établissement est exclu pour l'année #{selected_school_year}
    - elsif current_establishment.fetching_students
      = dsfr_alert(type: :info, title: "Récupération des élèves en cours") do
        %p Nous sommes en train de récupérer les données de vos élèves, veuillez rafraichir la page dans quelques minutes.
    - else
      .container
        = render partial: "home_timeline"

app/views/home/legal.html.haml
%h2 Finalités

%p 
  L'application informatique APLyPro permet le versement aux élèves de lycées professionnels inscrits dans des formations professionnelles des ministères chargés de l'éducation nationale, de l'agriculture et de la mer, de niveau 3 et 4, d'une allocation de valorisation de leurs périodes de formation en milieu professionnel.
%p
  Les informations recueillies dans le cadre de ce traitement sont également utilisées à des fins statistiques.

%h2 Base légale

%p
  Cette application informatique constitue un traitement de données à caractère personnel mis en œuvre par le ministère de l'Éducation nationale et de la Jeunesse pour le respect d'une obligation légale à laquelle le responsable du traitement est soumis au sens du c) du 1 de l'article 6 du règlement général sur la protection des données (RGPD).

%p 
  Le ministère s'engage à ce que la collecte et le traitement des données à caractère personnel, effectués à partir de l'application informatique APLyPro, soient conformes à ce règlement.

%h2 Données traitées et durée de conservation

%p Les informations proviennent du traitement Fédération d'identité du ministère (FIM) pour les personnels du ministère en charge de l'éducation nationale et ceux du ministère en charge de la mer, et du traitement FREGATA pour les personnels du ministère en charge de l'agriculture, et par renseignement direct de l'application pour les personnels désignés à la DGESCO, DGER et DGAMPA.

%p 
  Les données relatives aux chefs d'établissement, ainsi que les données relatives aux autres personnels sont conservées 10 ans dans l'application.

%h2 Destinataires

%p 
  Les destinataires sont les agents de la direction interministérielle du numérique (DINUM), les administrateurs du système d'information en académie, personnel du pôle de diffusion nationale, qui assurent l'assistance de l'application, les personnels désignés à la DGESCO, DGER et DGAMPA, et de l'agence de service et de paiement (ASP), qui assure le paiement et la réalisation des contrôles éventuels.

%h2 Droit des personnes

%p 
  Vous pouvez exercer vos droits d’accès, de rectification et de limitation prévus par les articles 15, 16 et 18 du RGPD et sur le fondement de l’obligation légale auprès de :

%ul
  %li votre chef d’établissement, si vous êtes personnel en établissement ;
  %li votre rectorat, si vous êtes chef d’établissement ou personnel en rectorat ;
  %li la DGESCO ou la DGER ou la DGAMPA, si vous êtes personnel de l’administration centrale.

%p Pour pouvez exercer ces droits sur place, par voie postale ou par voie électronique.

%p Les droits à l’effacement et à l’opposition ne s’appliquent pas au présent traitement.

%p Pour exercer vos droits ou pour toute autre question sur le traitement de vos données à caractère personnel, vous pouvez aussi contacter le délégué à la protection des données du ministère de l’Education nationale et de la Jeunesse :

%ul
  %li à l’adresse électronique suivante : dpd@education.gouv.fr

  %li 
    par courrier en vous adressant au : 

    %br
    Ministère de l'éducation nationale et de la jeunesse 
    %br
    À l'attention du délégué à la protection des données (DPD) 
    %br
    110 rue de Grenelle 
    %br
    75357 Paris Cedex 07 
    %br
    %br
    Si vous estimez, après nous avoir contactés, que vos droits ne sont pas respectés, vous pouvez adresser une réclamation à la CNIL :
  
  %li 
    via le formulaire de saisine en ligne : 
    = dsfr_link_to "https://www.cnil.fr/fr/vous-souhaitez-contacter-la-cnil", href: "https://www.cnil.fr/fr/vous-souhaitez-contacter-la-cnil"
      
  
  %li 
    ou par courrier postal, à l’adresse :

    %br
    Commission nationale de l'informatique et des libertés
    %br
    3 Place de Fontenoy
    %br
    TSA 80715
    %br
    75334 Paris Cedex 07

%p 
  À l’occasion de ces démarches, vous devez justifier de votre identité par tout moyen. En cas de doute sur votre identité, les services chargés du droit d’accès et le délégué à la protection des données peuvent vous demander les informations supplémentaires qui leur apparaissent nécessaires, y compris la photocopie d’un titre d’identité portant votre signature.

app/views/home/login.html.haml
.fr-grid-row.fr-grid-row--gutters#login-page
  - User::OMNIAUTH_PROVIDERS.each do |provider|
    .fr-col-md-6.fr-col-12
      = render 'shared/connection_panel',
        name: t("omniauth.#{provider}.title"),
        description: t("omniauth.#{provider}.description"),
        button: t("omniauth.#{provider}.button"),
        path: "/users/auth/#{provider}"

  .fr-col-md-6.fr-col-12
    = render 'shared/connection_panel',
      name: t("omniauth.mer.title"),
      description: t("omniauth.mer.description"),
      button: t("omniauth.mer.button"),
      path: "/users/auth/fim"

%hr.fr-mt-3w

= render 'shared/faq'

app/views/home/maintenance.html.haml
.fr-grid-row
  .fr-col-md-6
    %h1 APLyPro n'est pas disponible pour le moment.

    %p= @msg

    %hr

.fr-grid-row
  = render 'shared/faq'

app/views/home/welcome.html.haml
.fr-col-md-6
  %p.fr-text--lead
    Dans le cadre de la réforme des lycées professionnels,
    depuis la rentrée scolaire 2023, les lycéens professionnels
    perçoivent une allocation versée au titre des PFMP réalisées.

  %p.fr-text--lead
    APLyPro permet la gestion du versement de l’allocation par
    les établissements : la saisie du nombre de jours de PFMP
    réalisés ainsi que la saisie des coordonnées de paiement.

  %p
    Des documents ressources sont disponibles
    = dsfr_link_to "sur Eduscol", "https://eduscol.education.fr/3860/allocation-de-stage-au-lycee-professionnel"
    \.

  = link_to "Continuer", school_year_home_path(selected_school_year), class: 'fr-btn'