config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"

# rubocop:disable Metrics/BlockLength
Rails.application.routes.draw do
  namespace :asp do
    resources :schoolings, only: %i[index show] do
      member do
        post :generate_liquidation
        get :download_liquidation
      end
    end

    devise_for :users, skip: :all, class_name: "ASP::User"
  end

  # this allows overriding the redirect-if-not-logged-in path that
  # Devise automatically looks for with "new_#{resource}_session_url"
  # path[1], but we need to get it out of the scoped block above
  # otherwise it ends up being `asp_new_asp_user_session_path`.

  # [1]: https://github.com/heartcombo/devise/blob/bb18f4d3805be0bf5f45e21be39625c7cfd9c1d6/lib/devise/failure_app.rb#L140
  get "asp/login", to: "asp/application#login", as: :new_asp_user_session

  delete "asp/logout", to: "asp/application#logout", as: :destroy_asp_user_session

  namespace :academic do
    root to: "application#home"
    get "home", to: "application#home"
    get "academic_map", to: "application#academic_map"

    resources :establishments, only: [:show] do
      member do
        get :users
      end
      resources :classes, only: [:index]
    end

    resources :classes, only: [:show]

    resource :students do
      get :search_results
    end

    resources :students do
      get :show
      resources :pfmps, only: [:show]
    end

    resources :school_years, path: :year, only: [] do
      get "selected"

      collection do
        get "select"
      end
    end

    resources :users, only: [:index]

    resource :users, only: [] do
      get "select_academy"
      post "set_selected_academy"
    end

    resources :tools, only: [:index] do
      collection do
        post "remove_keycloak_user"
        post "invite_keycloak_user"
        get "academic_invitations"
        get "establishment_invitations"
      end
    end

    resources :academic_invitations, only: [:destroy]

    resources :reports, only: %i[index show] do
      collection do
        get :global_evolution
        post :export_evolution
      end
      member do
        get :global
        post :export
        get :establishments_table
      end
    end

    devise_for :users, class_name: "Academic::User"
  end

  get "academic/login", to: "academic/application#login", as: :new_academic_user_session

  delete "academic/logout", to: "academic/application#logout", as: :destroy_academic_user_session

  resources :users, only: :update do
    get "select_establishment"
  end

  resources :establishments, only: %w[edit update] do
    resources :invitations
  end

  resource :students do
    get "search_results"
  end

  resources :students, only: %i[show] do
    resources :ribs, only: %i[new create update edit]
  end

  resources :school_years, path: :year, only: [] do
    get "selected"

    collection do
      get "select"
    end

    get "/home", to: "home#home"

    resources :establishments, only: [] do
      post "create_attributive_decisions"
      post "reissue_attributive_decisions"
      post "download_attributive_decisions"
    end

    resources :classes, only: %i[show index] do
      member do
        get "bulk_pfmp"
        post "create_bulk_pfmp"
        get "bulk_pfmp_completion"
        put "update_bulk_pfmp"
        get "validation", to: "validations#show"
        post "validation", to: "validations#validate"
      end

      resources :ribs, only: [] do
        collection do
          get "missing"
          post "bulk_create"
        end
      end

      resources :schoolings, only: [:update] do
        member do
          get "confirm_abrogation"
          delete "abrogate_decision"
          get "confirm_cancellation_decision"
          get "cancellation_decision"
          get "confirm_da_extension"
          get "confirm_removal"
          get "confirm_removal_cancellation"
          post "remove"
          post "create_attributive_decision"
        end

        resources :pfmps, except: :index do
          member do
            post :validate
            get :confirm_deletion
            get :confirm_rectification
            post :rectify
            resources :payment_requests, only: %i[create update]
          end
        end
      end
    end

    resources :validations, only: :index
    resources :abrogations, only: :index
  end

  devise_scope :asp_user do
    get "/auth/asp/callback", to: "users/omniauth_callbacks#asp"
    post "/auth/asp_developer/callback", to: "users/omniauth_callbacks#asp_developer"
  end

  devise_scope :academic_user do
    get "/auth/academic/callback", to: "users/omniauth_callbacks#academic"
    post "/auth/academic_developer/callback", to: "users/omniauth_callbacks#academic_developer"
  end

  devise_for :users

  devise_scope :user do
    %w[fim masa developer].each do |action|
      match "/users/auth/#{action}/callback", to: "users/omniauth_callbacks##{action}", via: %i[get post]
    end

    get "/users/auth/failure", to: "users/omniauth_callbacks#failure"

    get "login", to: "home#login", as: :new_user_session
    delete "sign_out", to: "devise/sessions#destroy", as: :destroy_user_session
  end

  root "home#index"

  get "/welcome", to: "home#welcome"
  get "/home", to: "home#home"
  get "/accessibility", to: "home#accessibility"

  get "/maintenance", to: "home#maintenance"
  get "/legal", to: "home#legal"
  get "/faq", to: "home#faq"

  resources :stats, only: [:index] do
    collection do
      get "paid_pfmps_per_month"
    end
  end

  if Rails.env.production?
    Sidekiq::Web.use(Rack::Auth::Basic) do |user, password|
      # https://github.com/sidekiq/sidekiq/wiki/Monitoring#rails-http-basic-auth-from-routes
      # Protect against timing attacks:
      # - See https://codahale.com/a-lesson-in-timing-attacks/
      # - See https://thisdata.com/blog/timing-attacks-against-string-comparison/
      # - Use & (do not use &&) so that it doesn't short circuit.
      # - Use digests to stop length information leaking

      allowed_user = Digest::SHA256.hexdigest(ENV.fetch("APLYPRO_SIDEKIQ_USER", nil))
      allowed_password = Digest::SHA256.hexdigest(ENV.fetch("APLYPRO_SIDEKIQ_PASSWORD", nil))

      Rack::Utils.secure_compare(Digest::SHA256.hexdigest(user), allowed_user) &
        Rack::Utils.secure_compare(Digest::SHA256.hexdigest(password), allowed_password)
    end
  end

  mount Sidekiq::Web => "/sidekiq"
end
# rubocop:enable Metrics/BlockLength

app/controllers/academic/classes_controller.rb
# frozen_string_literal: true

module Academic
  class ClassesController < Academic::ApplicationController
    before_action :set_classe, only: :show

    def index
      infer_page_title

      @establishment = Establishment.joins(:classes)
                                    .where(academy_code: selected_academy,
                                           "classes.school_year_id": selected_school_year)
                                    .find(params[:establishment_id])

      @classes = @establishment.classes
                               .where(school_year: selected_school_year)
                               .includes(:mef, :school_year)
                               .left_joins(:active_schoolings)
                               .select("classes.*, COUNT(schoolings.id) AS active_students_count")
                               .group("classes.id")
                               .order(:label)
    end

    def show
      @page_title = @classe.to_s

      @schoolings = @classe.schoolings.includes(
        :student,
        :attributive_decision_attachment
      ).order("students.last_name, students.first_name")
    end

    private

    def set_classe
      @classe = Classe.joins(:establishment)
                      .where(establishments: { academy_code: selected_academy },
                             school_year_id: selected_school_year)
                      .find(params[:id])
    end
  end
end

app/controllers/classes_controller.rb
# frozen_string_literal: true

class ClassesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_classe, except: :index

  before_action :add_bulk_action_breadcrumbs, only: %i[
    create_bulk_pfmp
    bulk_pfmp
    bulk_pfmp_completion
    update_bulk_pfmp
  ]

  def index
    infer_page_title

    @classes = current_establishment.classes.where(school_year: selected_school_year)
    @classes_facade = ClassesFacade.new(@classes, current_establishment)
  end

  def show
    add_breadcrumb t("pages.titles.classes.index"), school_year_classes_path(selected_school_year)
    infer_page_title(name: @classe)

    @classe_facade = ClasseFacade.new(@classe)
  end

  def create_bulk_pfmp
    if @classe.create_bulk_pfmp(pfmp_params)
      redirect_to school_year_class_path(selected_school_year, @classe), notice: t("pfmps.new.success")
    else
      @pfmp = Pfmp.new(pfmp_params)
      # TODO: clean up this hack, here we set a schooling to run conditional validations
      @pfmp.schooling = @classe.schoolings.last
      @pfmp.save # save to populate the errors hash
      @pfmp.errors.delete(:schooling) # remove the one about schooling
      render :bulk_pfmp, status: :unprocessable_content
    end
  end

  def bulk_pfmp
    @pfmp = Pfmp.new
  end

  def bulk_pfmp_completion
    @pfmps = @classe
             .pfmps
             .in_state(:pending)
             .sort_by { |pfmp| [pfmp.schooling.student.last_name, pfmp.schooling.student.first_name, pfmp.start_date] }
  end

  def update_bulk_pfmp
    @pfmps = bulk_pfmp_completion_params[:pfmps].map do |pfmp_params|
      @classe.pfmps.find(pfmp_params[:id]).tap do |pfmp|
        PfmpManager.new(pfmp).update(day_count: pfmp_params[:day_count])
      end
    end

    if @pfmps.all?(&:save)
      redirect_to school_year_class_path(selected_school_year, @classe), notice: t("pfmps.update.success")
    else
      render :bulk_pfmp_completion, status: :unprocessable_content
    end
  end

  private

  def pfmp_params
    params.require(:pfmp).permit(
      :start_date,
      :end_date
    )
  end

  def bulk_pfmp_completion_params
    params.require(:classe).permit(
      pfmps: %i[id day_count]
    )
  end

  def set_classe
    @classe = current_establishment.classes.find_by!(id: params[:id], school_year: selected_school_year)
  rescue ActiveRecord::RecordNotFound
    redirect_to school_year_classes_path(selected_school_year),
                alert: t("errors.classes.not_found") and return
  end

  def add_bulk_action_breadcrumbs
    add_breadcrumb(
      t("pages.titles.classes.index"),
      school_year_classes_path(selected_school_year)
    )
    add_breadcrumb(
      t("pages.titles.classes.show", name: @classe),
      school_year_class_path(selected_school_year, @classe)
    )
    infer_page_title
  end
end

app/helpers/classes_helper.rb
# frozen_string_literal: true

module ClassesHelper
  def ribs_progress_badge(schoolings, **args)
    schoolings = schoolings.without_removed_students

    count = schoolings.joins(student: :ribs)
                      .where(ribs: { archived_at: nil, establishment: current_establishment })
                      .distinct(:"students.id")
                      .count(:"students.id")

    total = schoolings.select(:student_id).distinct.count

    progress_badge(count, total, **args)
  end

  def attributive_decisions_progress_badge(schoolings, **args)
    count = schoolings.with_attributive_decisions.count
    total = schoolings.without_removed_students.size

    progress_badge(count, total, **args)
  end

  def nb_pfmps(schoolings)
    schoolings.joins(:pfmps).count(:"pfmps.id")
  end

  def closed_schooling_information_tag(schooling, **args)
    return if schooling.blank?

    if schooling.removed?
      content_tag(
        :div,
        "Masqué(e) manuellement de la classe",
        class: "fr-badge fr-badge--sm fr-badge--warning #{args[:class]}"
      )
    elsif schooling.closed?
      content_tag(
        :div,
        "Sorti(e) de la classe",
        class: "fr-badge fr-badge--sm fr-badge--warning #{args[:class]}"
      )
    end
  end

  def extended_end_date_information_tag(schooling, **args)
    return if schooling.blank? || schooling.extended_end_date.blank?

    content_tag(
      :div,
      "Date de report : #{format_date(schooling.extended_end_date)}",
      class: "fr-badge fr-badge--sm fr-badge--info #{args[:class]}"
    )
  end

  def amounts_yearly_reached_information_tag(schooling, **args)
    return if schooling.pfmps.empty? || !schooling.pfmps.first.amounts_yearly_exceeded?

    content_tag(
      :div,
      "Plafond atteint",
      class: "fr-badge fr-badge--sm fr-badge--warning #{args[:class]}"
    )
  end

  private

  def progress_badge(count, total, **args)
    count ||= 0
    status = progress_badge_status(count, total)

    content_tag(:div, title: args[:title]) do
      dsfr_badge(status: status, html_attributes: { class: ["fr-badge counter"] }) do
        "#{count} / #{total}"
      end
    end
  end

  def progress_badge_status(count, total)
    if total.nil? || total.zero?
      :error
    else
      case count / total
      when 0..0.5
        :error
      when 0.51..0.99
        :warning
      when 1
        :success
      end
    end
  end
end

app/views/classes/_alert_apprentices.html.haml
.fr-callout.fr-col-lg-7
  %h3.fr-callout__title.fr-h5 Les apprentis ne sont pas bénéficiaires de l'allocation
  %p.fr-callout__text.fr-text--md
    Si des apprentis apparaissent dans vos classes, ils ne sont pas concernés par l'allocation. Nous allons bientôt les retirer d'APLyPro, vous devez les ignorer lors de vos saisies.

app/views/classes/_attributive_decisions_panel.html.haml
.fr-grid-row.fr-grid-row--top
  %h2.fr-col 1. Décisions d'attribution
  = attributive_decisions_progress_badge(@establishment_facade.selected_schoolings, title: "Les décisions d'attribution sont générés pour chaque scolarité,\ny compris pour les élèves sortis de classes.")
%p La décision d'attribution annuelle rend éligible l'élève à percevoir l'allocation, et ce pour chaque classe dans laquelle il a effectué une scolarité.

%p Ce document doit obligatoirement être transmis à l'élève et conservé toute l'année scolaire et il doit être archivé par l'établissement pendant une durée de 10 ans en cas de contrôle de la chaîne des dépenses publiques.


- if current_establishment.some_attributive_decisions_generating?(selected_school_year)
  = dsfr_alert(type: :info, title: t("panels.attributive_decisions.generating.title.other"), html_attributes: { class: 'fr-mt-3w' }) do
    %p= t("panels.attributive_decisions.generating.body.other")
- else
  .buttons-group
    - if current_establishment.some_attributive_decisions?(selected_school_year)
      = attributive_decisions_download_button

    - if current_user.can_try_to_generate_attributive_decisions?
      - if current_establishment.missing_attributive_decisions?(selected_school_year)
        = attributive_decisions_generation_form
      - if current_establishment.some_attributive_decisions?(selected_school_year)
        = render partial: "home/attributive_decision_reissue_form"

app/views/classes/_pfmps_payments_table.html.haml
- schooling.pfmps.each do |pfmp|
  .fr-grid-row
    .fr-col-md-7
      = dsfr_link_to pfmp.listing_to_s, school_year_class_schooling_pfmp_path(selected_school_year, @classe, schooling, pfmp), title: "#{pfmp.full_dates} : #{pfmp.day_count} jours"
    .fr-col-md-5
      -if pfmp.latest_payment_request.present?
        = pfmp.latest_payment_request.status_badge
= dsfr_link_to "Ajouter une PFMP individuelle", new_school_year_class_schooling_pfmp_path(selected_school_year, @classe, schooling)

app/views/classes/_students_hidden_table.html.haml
.fr-table.fr-table--no-caption
  %table
    %caption= "Élèves masqués manuellement de la classe"
    %thead
      %th{scope: "col"}
        Élèves
        = "(#{schoolings.count})"
      %th{scole: "col"}
        .fr-grid-row
          .fr-mr-1w Réintégration de l'élève dans la classe

    %tbody
      - schoolings.each do |schooling|
        - student = schooling.student
        %tr
          %td
            = dsfr_link_to student.index_name, student_path(student), title: t("links.students.show", name: student)
          %td
            = link_to "Réintégrer #{student} dans la classe #{@classe.label}", confirm_hidden_cancellation_school_year_class_schooling_path(selected_school_year, @classe, schooling), class: 'fr-btn fr-btn--primary'

app/views/classes/_students_removed_table.html.haml
.fr-table.fr-table--no-caption
  %table
    %caption= "Élèves masqués manuellement de la classe"
    %thead
      %th{scope: "col"}
        Élèves
        = "(#{schoolings.count})"
      %th{scole: "col"}
        .fr-grid-row
          .fr-mr-1w Réintégration de l'élève dans la classe

    %tbody
      - schoolings.each do |schooling|
        - student = schooling.student
        %tr
          %td
            = dsfr_link_to student.full_name, student_path(student), title: t("links.students.show", name: student)
          %td
            = link_to "Réintégrer #{student} dans la classe #{@classe.label}", confirm_removal_cancellation_school_year_class_schooling_path(selected_school_year, @classe, schooling), class: 'fr-btn fr-btn--primary'

app/views/classes/_students_table.html.haml
.fr-table.fr-table--no-caption
  %table
    %caption= caption
    %thead
      %th{scope: "col"}
        Élèves
        = "(#{schoolings.count})"
      %th{scole: "col"}
        .fr-grid-row
          .fr-mr-1w Décisions d'attribution
          = attributive_decisions_progress_badge(schoolings)
      %th{scope: "col"}
        .fr-grid-row
          .fr-mr-1w Coordonnées bancaires
          = ribs_progress_badge(schoolings)
      %th{scope: "col"}
        PFMPs et Paiements
        = "(#{nb_pfmps(schoolings)})"

    %tbody
      - schoolings.each do |schooling|
        - student = schooling.student
        %tr
          %td
            = dsfr_link_to student.full_name, student_path(student), title: t("links.students.show", name: student)
            %p= amounts_yearly_reached_information_tag(schooling)
          %td
            - if schooling.attributive_decision.present? && !schooling.abrogation_decision.present? && !schooling.cancellation_decision.present?
              %p= dsfr_badge(status: :success) { "Éditée" }
              - if schooling.extended_end_date.present?
                = dsfr_badge(status: :info) { "Reportée" }
            - else
              - if schooling.abrogation_decision.present?
                = dsfr_badge(status: :error) { "Abrogée" }
              - else
                = dsfr_badge(status: :error) { "Manquante" }
          %td
            - if student.rib(current_establishment).present?
              %p= dsfr_badge(status: :success) { "Saisies" }
              = dsfr_link_to "Modifier les coordonnées bancaires", edit_student_rib_path(student, student.rib(current_establishment))
            - else
              %p= dsfr_badge(status: :error) { "Non saisies" }
              = dsfr_link_to "Saisir les coordonnées bancaires", new_student_rib_path(student)
          %td
            = render partial: "pfmps_payments_table", locals: { schooling: schooling }

app/views/classes/bulk_pfmp.html.haml
.fr-grid-row
  .fr-col-md-6
    %p
      Ce formulaire vous permet d'anticiper les périodes de stage
      d'une classe en renseignant une même PFMP pour chacun de ses
      élèves.

.fr-grid-row
  .fr-col-md-6.fr-mb-3w
    = dsfr_alert(type: :warning, title: "La PFMP saisie au niveau de la classe est dupliquée pour chaque élève de la classe") do
      Important : Une PFMP saisie au niveau de la classe peut être modifiée au niveau de chaque élève.

= form_with model: @pfmp, url: create_bulk_pfmp_school_year_class_path(selected_school_year, @classe), builder: DsfrFormBuilder, data: { turbo: false } do |form|
  = form.dsfr_error_summary

  = form.dsfr_date_field(:start_date, width: 'sm-4 md-3 lg-2')
  = form.dsfr_date_field(:end_date, width: 'sm-4 md-3 lg-2')

  = form.dsfr_submit "Enregistrer"

app/views/classes/bulk_pfmp_completion.html.haml
.fr-col-md-6.fr-mb-3w
  = dsfr_alert(type: :warning, title: "Munissez-vous des attestations de fin de stage") do
    Le nombre de jours doit correspondre à celui qui figure dans l'attestation de fin de stage.

= form_with url: update_bulk_pfmp_school_year_class_path(selected_school_year, @classe), method: :put do |form|
  .fr-table.fr-table--no-caption
    %table
      %caption Liste des pfmps à compléter de la classe #{@classe.label}
      %thead
        %th{scope: "col"} Élève
        %th{scope: "col"} PFMP
        %th{scope: "col"} Nombre de jours
      %tbody
      - @pfmps.each do |pfmp|
        %tr
          %td
            - student = pfmp.schooling.student # need to go through schooling to prevent extra requests
            = dsfr_link_to student.full_name, student_path(student), title: t("links.students.show", name: student), tabindex: "1"
            .fr-mt-1w= closed_schooling_information_tag(pfmp.schooling)

          %td= dsfr_link_to pfmp.formatted_dates, school_year_class_schooling_pfmp_path(selected_school_year, @classe, pfmp.schooling, pfmp), tabindex: "1", title: pfmp.full_dates

          %td
            = form.hidden_field "classe[pfmps][][id]", value: pfmp.id
            = form.label "classe[pfmps][][day_count]", "Nombre de jours", class: "hidden"
            = form.number_field "classe[pfmps][][day_count]", value: pfmp.day_count, class: "fr-input fr-col-md-3 fr-col-sm-6 fr-col-xs-12"
            - if pfmp.errors.any?
              %p.fr-error-text= pfmp.errors.full_messages.join("\n")

  = form.submit "Enregistrer #{@pfmps.count} #{"PFMP".pluralize(@pfmps.count)}", class: "fr-btn fr-btn-primary"

app/views/classes/index.html.haml
= render partial: "alert_apprentices"

- if @classes.none?
  %p Récupération de la liste des élèves en cours (si ces derniers sont présents dans les bases de données de BEE [SYGNE] ou COLENTAGRI [FREGATA]).
- else
  .fr-table.fr-table--no-caption
    %table
      %caption.fr-h1 Liste des classes
      %thead
        %th{scope: "col"} Classe
        %th{scope: "col"} Décisions d'attribution
        %th{scope: "col"} Coordonnées bancaires
        %th{scope: "col"} PFMPs
        %th{scope: "col"} Paiements
      %tbody
        - @classes.each do |classe|
          %tr
            %td= dsfr_link_to classe.to_long_s, school_year_class_path(selected_school_year, classe), title: t("links.classes.show", label: classe.to_long_s)
            %td= attributive_decisions_progress_badge(classe.schoolings)
            %td= ribs_progress_badge(classe.schoolings)
            %td
              = pfmps_status_count_badge :pending, @classes_facade.nb_pfmps(classe.id, :pending)
              = pfmps_status_count_badge :completed, @classes_facade.nb_pfmps(classe.id, :completed)
              = pfmps_status_count_badge :validated, @classes_facade.nb_pfmps(classe.id, :validated)
            %td
              = payment_requests_status_count_badge :pending, @classes_facade.nb_payment_requests(classe, %i[pending ready])
              = payment_requests_status_count_badge :sent, @classes_facade.nb_payment_requests(classe, %i[sent integrated])
              = payment_requests_status_count_badge :incomplete, @classes_facade.nb_payment_requests(classe, %i[incomplete rejected unpaid])
              = payment_requests_status_count_badge :paid, @classes_facade.nb_payment_requests(classe, %i[paid])

app/views/classes/show.html.haml
= render partial: "alert_apprentices"

.actions.fr-btns-group.fr-btns-group--inline
  - if @classe_facade.nb_missing_ribs > 0
    = link_to @classe_facade.missing_ribs_button_text, missing_school_year_class_ribs_path(selected_school_year, @classe), class: 'fr-btn fr-btn--primary'

  - if @classe_facade.any_active_schoolings?
    = link_to 'Saisir une PFMP pour toute la classe', bulk_pfmp_school_year_class_path(selected_school_year, @classe), class: 'fr-btn fr-btn--primary'

.actions.fr-btns-group.fr-btns-group--inline
  - if @classe_facade.nb_pending_pfmps > 0
    = link_to bulk_pfmp_completion_school_year_class_path(selected_school_year, @classe), class: 'fr-btn fr-btn--secondary' do
      = @classe_facade.pending_pfmps_button_text
      = dsfr_badge(status: :new, html_attributes: { class: ["fr-badge--sm", "fr-ml-1w"] }) do
        = t("pfmps.states.pending")

  - if current_user.can_validate? && @classe_facade.nb_can_transition_to_validated_pfmps > 0
    = link_to validation_school_year_class_path(selected_school_year, @classe), class: 'fr-btn fr-btn--secondary' do
      = @classe_facade.can_transition_to_validated_pfmps_button_text
      = dsfr_badge(status: :info, html_attributes: { class: ["fr-badge--sm", "fr-ml-1w"] }) do
        = t("pfmps.states.completed")

= render partial: "students_table", locals: { schoolings: @classe_facade.schoolings.current, caption: "Liste des élèves" }

- if @classe.inactive_students.any?
  %h2 Élèves sortis de la classe
  = render partial: "students_table", locals: { schoolings: @classe_facade.schoolings.former, caption: "Élèves sortis de la classe" }

- if @classe.removed_students.any?
  %h2 Élèves masqués manuellement de la classe
  = render partial: "students_removed_table", locals: { schoolings: @classe_facade.schoolings.removed, caption: "Élèves masqués manuellement de la classe" }