config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"

# rubocop:disable Metrics/BlockLength
Rails.application.routes.draw do
  namespace :asp do
    resources :schoolings, only: %i[index show] do
      member do
        post :generate_liquidation
        get :download_liquidation
      end
    end

    devise_for :users, skip: :all, class_name: "ASP::User"
  end

  # this allows overriding the redirect-if-not-logged-in path that
  # Devise automatically looks for with "new_#{resource}_session_url"
  # path[1], but we need to get it out of the scoped block above
  # otherwise it ends up being `asp_new_asp_user_session_path`.

  # [1]: https://github.com/heartcombo/devise/blob/bb18f4d3805be0bf5f45e21be39625c7cfd9c1d6/lib/devise/failure_app.rb#L140
  get "asp/login", to: "asp/application#login", as: :new_asp_user_session

  delete "asp/logout", to: "asp/application#logout", as: :destroy_asp_user_session

  namespace :academic do
    root to: "application#home"
    get "home", to: "application#home"
    get "academic_map", to: "application#academic_map"

    resources :establishments, only: [:show] do
      member do
        get :users
      end
      resources :classes, only: [:index]
    end

    resources :classes, only: [:show]

    resource :students do
      get :search_results
    end

    resources :students do
      get :show
      resources :pfmps, only: [:show]
    end

    resources :school_years, path: :year, only: [] do
      get "selected"

      collection do
        get "select"
      end
    end

    resources :users, only: [:index]

    resource :users, only: [] do
      get "select_academy"
      post "set_selected_academy"
    end

    resources :tools, only: [:index] do
      collection do
        post "remove_keycloak_user"
        post "invite_keycloak_user"
        get "academic_invitations"
        get "establishment_invitations"
      end
    end

    resources :academic_invitations, only: [:destroy]

    resources :reports, only: %i[index show] do
      collection do
        get :global_evolution
        post :export_evolution
      end
      member do
        get :global
        post :export
        get :establishments_table
      end
    end

    devise_for :users, class_name: "Academic::User"
  end

  get "academic/login", to: "academic/application#login", as: :new_academic_user_session

  delete "academic/logout", to: "academic/application#logout", as: :destroy_academic_user_session

  resources :users, only: :update do
    get "select_establishment"
  end

  resources :establishments, only: %w[edit update] do
    resources :invitations
  end

  resource :students do
    get "search_results"
  end

  resources :students, only: %i[show] do
    resources :ribs, only: %i[new create update edit]
  end

  resources :school_years, path: :year, only: [] do
    get "selected"

    collection do
      get "select"
    end

    get "/home", to: "home#home"

    resources :establishments, only: [] do
      post "create_attributive_decisions"
      post "reissue_attributive_decisions"
      post "download_attributive_decisions"
    end

    resources :classes, only: %i[show index] do
      member do
        get "bulk_pfmp"
        post "create_bulk_pfmp"
        get "bulk_pfmp_completion"
        put "update_bulk_pfmp"
        get "validation", to: "validations#show"
        post "validation", to: "validations#validate"
      end

      resources :ribs, only: [] do
        collection do
          get "missing"
          post "bulk_create"
        end
      end

      resources :schoolings, only: [:update] do
        member do
          get "confirm_abrogation"
          delete "abrogate_decision"
          get "confirm_cancellation_decision"
          get "cancellation_decision"
          get "confirm_da_extension"
          get "confirm_removal"
          get "confirm_removal_cancellation"
          post "remove"
          post "create_attributive_decision"
        end

        resources :pfmps, except: :index do
          member do
            post :validate
            get :confirm_deletion
            get :confirm_rectification
            post :rectify
            resources :payment_requests, only: %i[create update]
          end
        end
      end
    end

    resources :validations, only: :index
    resources :abrogations, only: :index
  end

  devise_scope :asp_user do
    get "/auth/asp/callback", to: "users/omniauth_callbacks#asp"
    post "/auth/asp_developer/callback", to: "users/omniauth_callbacks#asp_developer"
  end

  devise_scope :academic_user do
    get "/auth/academic/callback", to: "users/omniauth_callbacks#academic"
    post "/auth/academic_developer/callback", to: "users/omniauth_callbacks#academic_developer"
  end

  devise_for :users

  devise_scope :user do
    %w[fim masa developer].each do |action|
      match "/users/auth/#{action}/callback", to: "users/omniauth_callbacks##{action}", via: %i[get post]
    end

    get "/users/auth/failure", to: "users/omniauth_callbacks#failure"

    get "login", to: "home#login", as: :new_user_session
    delete "sign_out", to: "devise/sessions#destroy", as: :destroy_user_session
  end

  root "home#index"

  get "/welcome", to: "home#welcome"
  get "/home", to: "home#home"
  get "/accessibility", to: "home#accessibility"

  get "/maintenance", to: "home#maintenance"
  get "/legal", to: "home#legal"
  get "/faq", to: "home#faq"

  resources :stats, only: [:index] do
    collection do
      get "paid_pfmps_per_month"
    end
  end

  if Rails.env.production?
    Sidekiq::Web.use(Rack::Auth::Basic) do |user, password|
      # https://github.com/sidekiq/sidekiq/wiki/Monitoring#rails-http-basic-auth-from-routes
      # Protect against timing attacks:
      # - See https://codahale.com/a-lesson-in-timing-attacks/
      # - See https://thisdata.com/blog/timing-attacks-against-string-comparison/
      # - Use & (do not use &&) so that it doesn't short circuit.
      # - Use digests to stop length information leaking

      allowed_user = Digest::SHA256.hexdigest(ENV.fetch("APLYPRO_SIDEKIQ_USER", nil))
      allowed_password = Digest::SHA256.hexdigest(ENV.fetch("APLYPRO_SIDEKIQ_PASSWORD", nil))

      Rack::Utils.secure_compare(Digest::SHA256.hexdigest(user), allowed_user) &
        Rack::Utils.secure_compare(Digest::SHA256.hexdigest(password), allowed_password)
    end
  end

  mount Sidekiq::Web => "/sidekiq"
end
# rubocop:enable Metrics/BlockLength

app/controllers/academic/academic_invitations_controller.rb
# frozen_string_literal: true

module Academic
  class AcademicInvitationsController < Academic::ApplicationController
    def destroy
      @invitation = current_user.invitations.find(params[:id])
      @invitation.destroy
      redirect_to academic_invitations_academic_tools_path,
                  notice: t(".success")
    rescue ActiveRecord::RecordNotFound
      redirect_to academic_invitations_academic_tools_path,
                  alert: t(".unauthorized")
    end
  end
end

app/controllers/academic/application_controller.rb
# frozen_string_literal: true

module Academic
  class ApplicationController < ActionController::Base
    include UserLogger
    include PageTitle
    include SelectedSchoolYear

    layout "academic"

    before_action :authenticate_academic_user!,
                  :check_selected_academy,
                  except: %i[login logout set_selected_academy]

    before_action :log_user,
                  :set_overrides,
                  :infer_page_title

    helper_method :current_user, :selected_academy, :authorised_academy_codes, :selected_school_year

    def home; end

    def academic_map
      @establishments_data = establishments_data_from_report

      respond_to do |format|
        format.html { render "academic_map", layout: false }
        format.turbo_stream
      end
    rescue ReportNotFoundError => e
      handle_missing_report_error(e)
    rescue ActiveRecord::QueryAborted, ActiveRecord::StatementInvalid, Timeout::Error => e
      handle_academic_map_error(e)
    end

    def login
      @inhibit_banner = true
    end

    def logout
      sign_out(current_academic_user)
      reset_session

      redirect_to after_sign_out_path_for(:academic_user)
    end

    protected

    def after_sign_out_path_for(_resource)
      new_academic_user_session_path
    end

    def current_user
      current_academic_user
    end

    def set_overrides
      @inhibit_nav = false
      @inhibit_title = true
      @logout_path = :destroy_academic_user_session
    end

    def selected_academy
      @selected_academy ||= session[:selected_academy]
    end

    def authorised_academy_codes
      @authorised_academy_codes ||= session[:academy_codes]
    end

    def check_selected_academy
      return unless selected_academy.nil?

      redirect_to select_academy_academic_users_path(current_user)
    end

    private

    def handle_academic_map_error(error)
      Rails.logger.error("Academic map loading failed: #{error.message}")

      respond_to do |format|
        format.html { render "academic_map_error", layout: false, status: :service_unavailable }
        format.turbo_stream { render turbo_stream: turbo_stream.replace("academic_map", partial: "academic_map_error") }
      end
    end

    def handle_missing_report_error(error)
      Rails.logger.error("No report available for academic map: #{error.message}")

      respond_to do |format|
        format.html { render "academic_map_missing_report", layout: false, status: :not_found }
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace("academic_map", partial: "academic_map_missing_report")
        end
      end
    end

    def establishments_data_from_report
      report = current_report
      raise ReportNotFoundError, selected_school_year if report.nil?

      Academic::EstablishmentsReportExtractor
        .new(report, selected_academy, selected_school_year)
        .extract_establishments_data
    end

    def current_report
      @current_report ||= Report.select(:id, :school_year_id, :created_at)
                                .for_school_year(selected_school_year)
                                .latest
    end
  end
end

app/controllers/academic/classes_controller.rb
# frozen_string_literal: true

module Academic
  class ClassesController < Academic::ApplicationController
    before_action :set_classe, only: :show

    def index
      infer_page_title

      @establishment = Establishment.joins(:classes)
                                    .where(academy_code: selected_academy,
                                           "classes.school_year_id": selected_school_year)
                                    .find(params[:establishment_id])

      @classes = @establishment.classes
                               .where(school_year: selected_school_year)
                               .includes(:mef, :school_year)
                               .left_joins(:active_schoolings)
                               .select("classes.*, COUNT(schoolings.id) AS active_students_count")
                               .group("classes.id")
                               .order(:label)
    end

    def show
      @page_title = @classe.to_s

      @schoolings = @classe.schoolings.includes(
        :student,
        :attributive_decision_attachment
      ).order("students.last_name, students.first_name")
    end

    private

    def set_classe
      @classe = Classe.joins(:establishment)
                      .where(establishments: { academy_code: selected_academy },
                             school_year_id: selected_school_year)
                      .find(params[:id])
    end
  end
end

app/controllers/academic/establishments_controller.rb
# frozen_string_literal: true

module Academic
  class EstablishmentsController < Academic::ApplicationController
    include UserFiltering

    before_action :find_establishment

    helper_method :current_establishment

    def show
      @directors = User.joins(establishment_user_roles: :establishment)
                       .where(establishment_user_roles: { role: :dir, establishment_id: @etab.id })
                       .distinct
      @establishment_data = establishment_data_from_report
    end

    def users
      @search_query = normalize_search_query
      @users = filtered_establishment_users
      @establishment_eurs_by_user = load_establishment_user_roles
    end

    private

    def filtered_establishment_users
      User.joins(establishment_user_roles: :establishment)
          .where(establishment_user_roles: { establishment_id: @etab.id })
          .then { |relation| apply_search(relation) }
          .then { |relation| filter_by_role(relation) }
          .then { |relation| apply_user_sorting(relation) }
          .page(params[:page])
          .per(users_per_page)
    end

    def current_establishment
      @current_establishment ||= @etab
    end

    def find_establishment
      @etab = Establishment.joins(:classes)
                           .where(academy_code: selected_academy,
                                  "classes.school_year_id": selected_school_year)
                           .find(params.require(:id))
      @establishment_facade = EstablishmentFacade.new(current_establishment, selected_school_year)
    end

    def establishment_data_from_report
      report = current_report
      raise ReportNotFoundError, selected_school_year if report.nil?

      extractor = Academic::EstablishmentsReportExtractor.new(report, selected_academy, selected_school_year)
      data = extractor.extract_single_establishment_data(@etab.uai)

      return {} if data.nil?

      { @etab.uai => data }
    end

    def load_establishment_user_roles
      EstablishmentUserRole
        .where(user_id: @users.reorder(nil).pluck(:id), establishment_id: @etab.id)
        .includes(:establishment)
        .group_by(&:user_id)
    end
  end
end

app/helpers/academic/application_helper.rb
# frozen_string_literal: true

module Academic
  module ApplicationHelper
    def sortable_column_header(column:, label:, path:, current_sort:, **options)
      is_active = (current_sort.blank? && column == "name") || current_sort == column
      css_class = ["fr-link", ("fr-text--heavy" if is_active)].compact.join(" ")
      title = "Trier par #{label.downcase}"

      link_to path, class: css_class, title: title, **options do
        concat label
        concat " "
        concat content_tag(:i, "", class: "fr-icon-arrow-down-s-line fr-icon--sm") if is_active
      end
    end

    def sortable_table_hint
      content_tag(:p, class: "fr-text--sm fr-text--mention-grey fr-mb-1w") do
        concat content_tag(:i, "", class: "fr-icon-arrow-up-down-line fr-icon--sm")
        concat " "
        concat "Cliquez sur les en-têtes de colonne pour trier"
      end
    end
  end
end

app/helpers/academic/stats_helper.rb
# frozen_string_literal: true

module Academic
  module StatsHelper
    def format_stat_value(value, indicator_type: nil)
      return handle_special_values(value) unless valid_numeric?(value)

      if currency_indicator?(indicator_type)
        number_to_currency(value, unit: "€", separator: ",", delimiter: " ", precision: 2)
      elsif indicator_type == "Stats::Ratio"
        number_to_percentage(value * 100, precision: 2, separator: ",")
      elsif indicator_type == "Stats::Count" || integer_value?(value)
        number_with_delimiter(value.to_i, delimiter: " ")
      else
        number_with_precision(value, precision: 2, separator: ",", delimiter: " ")
      end
    end

    def cell_background_color(value, indicator_type: nil)
      return "" unless indicator_type == "Stats::Ratio"
      return "" unless value.is_a?(Numeric) && ratio_value?(value)

      if value >= 0.8
        "background-color: var(--success-950-100);"
      elsif value >= 0.5
        "background-color: var(--yellow-tournesol-975-75);"
      elsif value >= 0.2
        "background-color: var(--yellow-tournesol-850-200);"
      else
        "background-color: var(--red-marianne-950-100);"
      end
    end

    def format_table_header(key)
      return key.to_s unless key.is_a?(Symbol) || key.is_a?(String)

      symbol_key = key.is_a?(Symbol) ? key : key.to_sym
      I18n.t("activerecord.attributes.report.#{symbol_key}", default: symbol_key.to_s.humanize)
    end

    private

    def handle_special_values(value)
      return "N/A" if value.nil?
      return "Infini" if value.respond_to?(:infinite?) && value.infinite?
      return "0" if value.respond_to?(:nan?) && value.nan?

      value.to_s
    end

    def valid_numeric?(value)
      value.is_a?(Numeric)
    end

    def currency_indicator?(indicator_type)
      indicator_type == "Stats::Sum"
    end

    def ratio_value?(value)
      value.is_a?(Float) && value >= 0 && value <= 1
    end

    def integer_value?(value)
      value.is_a?(Integer) || (value.is_a?(Numeric) && value == value.to_i)
    end
  end
end

app/helpers/academic/students_helper.rb
# frozen_string_literal: true

module Academic
  module StudentsHelper
    def schoolings_with_pfmps(schoolings)
      schoolings.select { |s| s.pfmps.any? }
    end

    def pfmps?(schoolings)
      schoolings_with_pfmps(schoolings).any?
    end
  end
end

app/helpers/academic/users_helper.rb
# frozen_string_literal: true

module Academic
  module UsersHelper
    def user_role_badges(roles, establishment: nil, user: nil)
      badges = []
      badges << content_tag(:span, "Directeur", class: "fr-badge fr-badge--blue-ecume") if roles.include?("dir")
      if roles.include?("authorised")
        badges << content_tag(:span, "Habilité", class: "fr-badge fr-badge--purple-glycine fr-ml-1w")
      end
      if establishment && user && establishment.confirmed_director_id == user.id
        badges << content_tag(:span, "Confirmé", class: "fr-badge fr-badge--sm fr-badge--success fr-ml-1w")
      end

      safe_join(badges)
    end
  end
end

app/views/academic/establishments/_establishment_timeline.html.haml
.row
  %h2= "Année scolaire #{selected_school_year}"

- if @establishment_facade.students_count <= 0
  .row
    = t("errors.school_years.not_found").html_safe
- else
  - dsfr_colors = { blue: "#000091", light_blue: "#bccdff", green: "#88fdaa", red: "#ffbdbd" }

  .fr-container.fr-mb-5w
    .fr-grid-row.fr-grid-row--gutters.fr-mb-5w
      .fr-col-12.fr-col-lg-6
        .gray-panel.timeline-section.fr-p-3w
          .fr-grid-row.fr-grid-row--top
            %h2.fr-col 1. Décisions d'attribution
            = attributive_decisions_progress_badge(@establishment_facade.selected_schoolings, title: "Les décisions d'attribution sont générés pour chaque scolarité,\ny compris pour les élèves sortis de classes.")
          %p.fr-mb-2w La décision d'attribution annuelle rend éligible l'élève à percevoir l'allocation, et ce pour chaque classe dans laquelle il a effectué une scolarité.
          %p.fr-mb-3w Ce document doit obligatoirement être transmis à l'élève et conservé toute l'année scolaire et il doit être archivé par l'établissement pendant une durée de 10 ans en cas de contrôle de la chaîne des dépenses publiques.
          .chart-container.fr-mb-2w
            = pie_chart({ "Élèves avec DA" => @establishment_facade.attributive_decisions_count, "Élèves sans DA" => @establishment_facade.without_attributive_decisions_count }, colors: [dsfr_colors[:green], dsfr_colors[:red]], donut: true)

      .fr-col-12.fr-col-lg-6
        .gray-panel.timeline-section.fr-p-3w
          .fr-grid-row.fr-grid-row--top
            %h2.fr-col 2. Coordonnées bancaires
            = ribs_progress_badge(@etab.schoolings, title: "Les coordonnées bancaires sont réutilisées pour un même élève\nà travers toutes les classes qu'il a pu fréquenter.")
          %p.fr-mb-3w Afin de pouvoir verser l'allocation aux lycéens, APLyPro a besoin de leurs coordonnées bancaires, de celles d'un responsable légal ou d'un tiers.
          .chart-container.fr-mb-2w
            = pie_chart({ "Élèves avec RIB" => @establishment_facade.ribs_count, "Élèves sans RIB" => @establishment_facade.students_without_rib_count }, colors: [dsfr_colors[:green], dsfr_colors[:red]], donut: true)

    .fr-grid-row.fr-grid-row--gutters
      .fr-col-12.fr-col-lg-6
        .gray-panel.timeline-section.fr-p-3w
          %h2 3. Périodes de formation en milieu professionnel
          .fr-grid-row.fr-mb-2w
            - PfmpStateMachine.states.each_with_index do |state, index|
              - if index > 0
                .fr-mx-1w →
              = pfmps_status_count_badge(state.to_sym, @establishment_facade.pfmps_counts[state.to_sym], display_zero: true)
          %p.fr-mb-3w Pour calculer le montant des allocations à envoyer, APLyPro a besoin de connaître le nombre de jours travaillés des PFMPs de chaque élève.
          .chart-container.fr-mb-2w
            = column_chart(@establishment_facade.pfmps_counts.transform_keys { |key| t("pfmps.state.#{key}") },
              colors: [dsfr_colors[:light_blue], dsfr_colors[:red], dsfr_colors[:green], dsfr_colors[:red]],
              label: "PFMPs par états")

      .fr-col-12.fr-col-lg-6
        .gray-panel.timeline-section.fr-p-3w
          %h2 4. Demandes de paiements des PFMPs
          .fr-grid-row.fr-mb-2w
            - ASP::PaymentRequestDecorator::PAYMENT_STAGES.each_with_index do |states, index|
              - if index > 0
                .fr-mx-1w →
              .centering-container
                = payment_requests_status_count_badge(states.first, @establishment_facade.payment_requests_counts[states.first], display_zero: true)
                = payment_requests_status_count_badge(states.last, @establishment_facade.payment_requests_counts[states.last], display_zero: false)
          %p.fr-mb-3w La validation du chef d'établissement est nécessaire pour chaque PFMP. Une fois la PFMP validée, une demande de paiement est ensuite envoyée à l'Agence de Services et de Paiement (ASP). Chaque demande de paiement possède un statut affiché dans la page "Paiements".
          .chart-container.fr-mb-2w
            = column_chart(@establishment_facade.payment_requests_counts.transform_keys { |key| t("payment_requests.state.#{key}") },
              colors: [dsfr_colors[:blue], dsfr_colors[:red], dsfr_colors[:light_blue], dsfr_colors[:red], dsfr_colors[:green], dsfr_colors[:red]],
              label: "Demandes de paiements par états")

app/views/academic/establishments/show.html.haml
%h2.fr-mt-2w= "Établissement: #{@establishment_data[@etab.uai][:name]}"

.fr-container.fr-mb-2w
  = link_to "Retour à la carte des établissements", academic_home_path, class: "fr-btn fr-btn--secondary", data: { turbo: false }

.fr-container.fr-my-4w
  .fr-grid-row.fr-grid-row--gutters
    .fr-col-12.fr-col-md-6
      .fr-card.fr-card--shadow
        .fr-card__body
          %h3.fr-card__title Informations générales
          .fr-card__content
            %ul.fr-list
              %li
                %strong UAI:
                = @etab.uai
              - if @etab.telephone.present?
                %li
                  %strong Téléphone:
                  = @etab.telephone
              %li
                %strong Nombre de scolarités:
                = @establishment_data[@etab.uai][:schooling_count]
              %li
                %strong Montant payé:
                = number_to_currency(@establishment_data[@etab.uai][:paid_amount], unit: "€", format: "%n %u")
            .fr-mt-3w
              = link_to "Voir les Classes", academic_establishment_classes_path(@etab), class: "fr-btn fr-btn--secondary"

    .fr-col-12.fr-col-md-6
      .fr-card.fr-card--shadow
        .fr-card__body
          %h3.fr-card__title Directeurs associés
          .fr-card__content
            - if @directors.empty?
              .fr-alert.fr-alert--info
                %p.fr-alert__title Aucun directeur trouvé pour cet établissement.
            - else
              .fr-table.fr-table--no-caption
                %table
                  %caption Liste des directeurs de l'établissement
                  %thead
                    %tr
                      %th{scope: "col"} Nom
                      %th{scope: "col"} Email
                      %th{scope: "col"} Statut
                  %tbody
                    - @directors.each do |user|
                      %tr
                        %td
                          %strong= user.name
                        %td= user.email
                        %td
                          - if @etab.confirmed_director_id == user.id
                            %span.fr-badge.fr-badge--success
                              Directeur confirmé
                          - else
                            %span.fr-badge.fr-badge--info
                              Directeur non confirmé
            .fr-mt-3w
              = link_to "Voir tous les utilisateurs", users_academic_establishment_path(@etab), class: "fr-btn fr-btn--secondary"

.fr-container
  = render 'academic/establishments/establishment_timeline'

app/views/academic/establishments/users.html.haml
%section.fr-container.fr-pb-3w
  %h1.fr-h3 Utilisateurs de l'établissement #{@etab.name} - UAI #{@etab.uai}

  .fr-mb-3w
    = form_with method: :get, url: users_academic_establishment_path(@etab), local: true do |form|
      .fr-search-bar{role: "search"}
        = form.label :search, "Recherche", class: "fr-label"
        = form.text_field :search, placeholder: "Rechercher par nom ou email...", value: @search_query, class: "fr-input"
        = form.button "Rechercher", type: "submit", class: "fr-btn", name: nil

  .fr-mb-3w
    .fr-btns-group.fr-btns-group--inline
      = link_to "Tous", users_academic_establishment_path(@etab, search: @search_query), class: "fr-btn #{params[:role].blank? ? 'fr-btn--secondary' : 'fr-btn--tertiary'}"
      = link_to "Directeurs", users_academic_establishment_path(@etab, role: :dir, search: @search_query), class: "fr-btn #{params[:role] == 'dir' ? 'fr-btn--secondary' : 'fr-btn--tertiary'}"
      = link_to "Habilités", users_academic_establishment_path(@etab, role: :authorised, search: @search_query), class: "fr-btn #{params[:role] == 'authorised' ? 'fr-btn--secondary' : 'fr-btn--tertiary'}"

  - if @users.empty?
    .fr-alert.fr-alert--info
      %p.fr-alert__title Aucun utilisateur trouvé pour cet établissement.
  - else
    = sortable_table_hint
    .fr-table.fr-table--no-caption
      %table
        %caption Liste des utilisateurs de l'établissement
        %thead
          %tr
            %th{scope: "col"}
              = sortable_column_header(column: "name", label: "Nom", path: users_academic_establishment_path(@etab, role: params[:role], search: @search_query, sort: "name"), current_sort: params[:sort])
            %th{scope: "col"}
              = sortable_column_header(column: "email", label: "Email", path: users_academic_establishment_path(@etab, role: params[:role], search: @search_query, sort: "email"), current_sort: params[:sort])
            %th{scope: "col"} Rôle(s)
            %th{scope: "col"}
              = sortable_column_header(column: "last_sign_in", label: "Dernière connexion", path: users_academic_establishment_path(@etab, role: params[:role], search: @search_query, sort: "last_sign_in"), current_sort: params[:sort])
        %tbody
          - @users.each do |user|
            - establishment_eurs = @establishment_eurs_by_user[user.id] || []
            - user_roles = establishment_eurs.map(&:role).uniq
            %tr
              %td
                %strong= user.name
              %td= user.email
              %td
                = user_role_badges(user_roles, establishment: @etab, user: user)
              %td
                - if user.last_sign_in_at
                  = l(user.last_sign_in_at, format: :long)
                - else
                  %span.fr-text--sm.fr-text--mention-grey Jamais connecté

    .fr-mt-3w.d-flex.justify-content-center
      = paginate @users, params: { search: @search_query, role: params[:role], sort: params[:sort] }